name: Docker CI/CD for Coderacer Backend

on:
  push:
    branches:
      - main
      - cicd

env:
  IMAGE_NAME: coderacer-postgres # Name of your Docker image
  DOCKER_REGISTRY: ghcr.io      # Using GitHub Container Registry (ghcr.io)
  APP_PORT: 8000

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Spring Boot application with Maven
        run: mvn clean install -DskipTests
        working-directory: ./

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ lower(github.repository) }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.DOCKER_REGISTRY }}/${{ lower(github.repository) }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            APP_PORT=${{ env.APP_PORT }}
            SQL_DATABASE=${{ secrets.SQL_DATABASE }}
            SQL_USERNAME=${{ secrets.SQL_USERNAME }}
            SQL_PASSWORD=${{ secrets.SQL_PASSWORD }}
            EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }}
            EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
        env:
          SQL_DATABASE: ${{ secrets.SQL_DATABASE }}
          SQL_USERNAME: ${{ secrets.SQL_USERNAME }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
